### ISSUE TITLE
Notifications Improvement 

### ISSUE THREAD

**Issue by camo0067** [Horndev/zapread.com-issues#115]
![screenshot 2018-09-22 15 11 35](https://user-images.githubusercontent.com/42921424/45921380-fe34e600-be79-11e8-9b59-3a8e32caefa4.png)

Could the notification be formatted to include the User that is notifying? For example New Alert! You were mentioned in a comment by Zelgada. 

*Post thought* Maybe formatting exactly like the email notifications? Can this code be copied directly to Zapread notifications

**Comment by Horndev** [comment]
On it!

**Comment by Horndev** [comment]
Should now work correctly.  Still improving but basic functionality is there.
