### ISSUE TITLE
"Subscribe" button change to "Subscribed" upon click

### ISSUE THREAD

**Issue by camo0067** [Horndev/zapread.com-issues#122]
Hi I was a little confused today when following the new people we've seen come online recently. I was clicking the Subscribe button to follow these individuals and I was expecting the button to "grey out" or change from "Subscribe" to "Unsubscribe" or "Subscribed".

**Comment by Horndev** [comment]
Thanks for the UX tip.  I'll have a look and see what's happening with that.

**Comment by Horndev** [comment]
Now fixed.

I made the call async.  It was happening because it was a synchronous call with refresh, and the refresh didn't invalidate the cache.  Should now work as expected.
