### ISSUE TITLE
Comment: Edit/Preview - Toolbox

### ISSUE THREAD

**Issue by camo0067** [Horndev/zapread.com-issues#129]
![screenshot 2018-10-01 18 12 15](https://user-images.githubusercontent.com/42921424/46321436-eb708e80-c5a8-11e8-8b14-775b932c921c.png)

I went to post the picture and needed to edit the size, I also wanted to throw that URL as a hyperlink; but I didn't have a editor bar like when posting the comment. Is this possible to implementation, is it overkill to want a preview option on comments? - My head is thinking *Gorilla style posting* or *Graffiti someones post* - when you can make a comment look as good or better than the OP's (earning more votes too). 

Thoughts:    It would add a really interesting power dynamic when commenting, and it could allow authors the ability to *flair up* their entire thread, rather than limit them to only the original post.

**Comment by Horndev** [comment]
Nice.  I need to beef up the comment editing.  Thanks!

**Comment by Horndev** [comment]
Closing issue - I think the feature was implemented as requested.
