### ISSUE TITLE
links in answers are not clickable

### ISSUE THREAD

**Issue by renepickhardt** [Horndev/zapread.com-issues#29]
<img width="691" alt="bildschirmfoto 2018-08-26 um 10 14 02" src="https://user-images.githubusercontent.com/1926816/44626203-d6a13b00-a918-11e8-8b5b-334538578539.png">

**Comment by Horndev** [comment]
Will be addressed in next version.

**Comment by Horndev** [comment]
need to press space after link to make it clickable.
