### ISSUE TITLE
unexpected redirect to home page after commenting

### ISSUE THREAD

**Issue by renepickhardt** [Horndev/zapread.com-issues#31]
when leaving a comment e.g. on this page: 
http://www.zapread.com/Group/GroupDetail/8 within the issue tracker topic I will be beemed to the homepage after submission. that is unintuitive.

**Comment by Horndev** [comment]
Yes, the comment submission is not asynchronously implemented.  I will update it.

**Comment by Horndev** [comment]
Feature completed.  Implemented as of https://github.com/Horndev/zapread.com/commit/be6c1550b435950959969d4cd92ba76ff07c31d5
