### ISSUE TITLE
what is config option1 and config option2 ? 

### ISSUE THREAD

**Issue by renepickhardt** [Horndev/zapread.com-issues#36]
on http://www.zapread.com/Manage I can choose between config option1 and config option2 (: 

<img width="1474" alt="bildschirmfoto 2018-08-26 um 18 18 59" src="https://user-images.githubusercontent.com/1926816/44630389-e8a4cd00-a95c-11e8-8b17-7fe4a6509854.png">

**Comment by Horndev** [comment]
Those are template options - they don't do anything yet.  It was an idea to change the feed sort order, and other things.
