### ISSUE TITLE
spending history: entries not clickable

### ISSUE THREAD

**Issue by renepickhardt** [Horndev/zapread.com-issues#37]
the comment number is not so helpfull for me. it would be way better if each comment had a guid and I could klick on it: 
<img width="718" alt="bildschirmfoto 2018-08-26 um 18 29 00" src="https://user-images.githubusercontent.com/1926816/44630450-1b02fa00-a95e-11e8-93d0-11479f20a4dc.png">

**Comment by Horndev** [comment]
Just added that.  It will be linked to the comment in a future version.  Thanks for noticing.

**Comment by Horndev** [comment]
They should now be clickable.  Comments currently point to their parent posts.
