### ISSUE TITLE
Accumulate statistics for LN deposits and withdraws for Admin Page

### ISSUE THREAD

**Issue by Horndev** [Horndev/zapread.com-issues#43]

**Comment by camo0067** [comment]
There isn't an ability to withdraw yet? Analytics are working.

**Comment by Horndev** [comment]
You should be able to withdraw.  By admin page, I am referring to the site admin (which users don't see).  That's where the health of the site overall can be monitored (i.e. node is working and not throwing errors!)

**Comment by Horndev** [comment]
use this?  http://atashbahar.com/post/2017-04-27-group-by-day-week-month-quarter-and-year-in-entity-framework

**Comment by Horndev** [comment]
done!
