### ISSUE TITLE
Show groups users are subscribed to in user page.

### ISSUE THREAD

**Issue by Horndev** [Horndev/zapread.com-issues#74]

**Comment by camo0067** [comment]
Do the user feeds I see reflect that of the owner's subscription on that page? I haven't noticed a "re-post" feature, but for instance on Colleen's profile, I only see your posts, I was wondering if I am re-posting to my audience when I tip. When someone views my profile how do they see it? Is it by who I follow or what I have posted or tipped on?

**Comment by Horndev** [comment]
The feed on a user page reflects the owner's subscriptions and activities.  Since Colleen is subscribed to me, that page shows lots of my activity.

When they view your profile, they should see the same thing you see on your profile.

**Comment by Horndev** [comment]
moved to https://github.com/Horndev/zapread.com/issues/35
