### ISSUE TITLE
Pages not fitting correctly

### ISSUE THREAD

**Issue by camo0067** [Horndev/zapread.com-issues#80]
![screenshot 2018-09-02 21 46 40](https://user-images.githubusercontent.com/42921424/44965266-4b1c4100-aefa-11e8-9b7c-a37f5dd01074.png)
![screenshot 2018-09-02 21 45 24](https://user-images.githubusercontent.com/42921424/44965270-4c4d6e00-aefa-11e8-9b66-eb60ac449d54.png)

I was going for a couple of thins here. Is there scripting inside the text boxes? html no but maybe css or another language I am unfamiliar with. Can we edit the headers of our post? 

Second the images uploaded were large in file size, I was wondering if we can download the images later but there isn't an option to do so.

**Comment by Horndev** [comment]
I am not saving images at original quality (save cost for storage space).  I noticed that a few views of pages are not properly truncating the posts.  I will fix this

Yes, you can edit the header.  Click the down arrow top right of post and click Edit.

**Comment by Horndev** [comment]
Fixed in https://github.com/Horndev/zapread.com/commit/415ce0738f2e6c2564821f5e5f51881f11d7fe3c
